### PR TITLE
added strict param.  It's able to you use strict has_role?

### PR DESCRIPTION
**Pull request by sunchess**
```ruby
class User < ActiveRecord::Base
  rolify strict: true
end

@user = User.first

@user.add_role(:forum, Forum)
@user.add_role(:forum, Forum.first)

@user.has_role?(:forum, Froum) #=> true
@user.has_role?(:forum, Froum.first) #=> true
@user.has_role?(:forum, Froum.last) #=> false
```
I.e. you get true only on a role that you manually add.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
This is a good PR but the TravisCI build is currently failing a test for Mongoid. If you can correct this, we'll merge this into the project.

**Comment by sunchess** [comment]
Hm.. sorry but on my local laptop I haven't errors on tests. I really want to.
My PR not have changes gemfile or any config. Why can by the error "Don't know how to build task 'db:create'"?

**Comment by sunchess** [comment]
Hey, tests is fixed

**Comment by wldcordeiro** [comment]
Cool, thanks for the PR. Merging. :)

**Comment by sunchess** [comment]
Thank you guys. :)

**Comment by sunchess** [comment]
Can you fix some misprint in the readmy file?  instead of "Forum" I wrote Froum, sorry :(

**Pull request merged**
