### PR TITLE
Fixes #213: added without_role method for resources and users

### LINKED ISSUE #213: select users without roles
Hi
I'd like to query rolified User model for users **without** certain role, for example to make admins (which may or may not have moderator role) not visible for moderators on users list etc, is this possible? i'm not that good at sql and active record internals to make it by hand

i 'm using rolify 3.2.0 with rails 4.0.0

### PR DESCRIPTION
**Pull request by owenkelly**
I've added a without_role method for users and resources that works much the same way the with_role method works. I've also added tests for both methods.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
Thanks for the PR! It appears that currently your PR is unsuccessful with the Mongoid adapter though, if you can patch that up this is on its way to merging.

**Comment by wldcordeiro** [comment]
@owenkelly Any luck fixing the Mongoid adapter version?

**Comment by owenkelly** [comment]
Not yet -- I haven't worked much with mongoid in the past so I'm working on getting more familiar with it ATM. I'm hoping to have a fixed attempt in the next week or two.

**Comment by owenkelly** [comment]
Alright, I abstracted part of the without_role method I wrote into the active record and mongoid adapters and things seem to be working now. Let me know if there are any refactors you would like to see me make. It's worth noting that the resource_spec tests on lines 239, 262 and 272 were failing on my machine, but are passing on travis. I suspect the mongoid database is not getting cleaned up.

**Comment by wldcordeiro** [comment]
Thanks @owenkelly looks great, I'll be merging this and there should be a new version coming out in the next couple of weeks to Rubygems with this and other changes.

**Pull request merged**
