### PR TITLE
get CI building again

### PR DESCRIPTION
**Pull request by thomas-mcdonald**
partial fix for #530 without the documentation update

* set appropriate version constraints for activerecord 5
* add additional constraint for mongoid 7 to help bundler find a resolvable set of gems
* specify gem has a dependency on Railties in the gemspec

### CODE REVIEW

**Comment by EppO** [comment]
Hakiri is complaining because you're not strict enough on the railties version
https://hakiri.io/github/RolifyCommunity/rolify/master/e2fd2ec9958a31fd49e5e44b1fde4ac965e422b9/warnings?name=Code+Injection

You need to be sure to run railties 5.2.2.1+ in your version constraints. I would change all rails versions for the Rails 5 Gemfile to `gem "railties", "~> 5.2.4`

**Comment by thomas-mcdonald** [comment]
@EppO I think it's actually failing because of the requirement for `railties > 4.2` I added to the gemspec. Not sure what to do here - I think the gem should properly declare the versions we support (so when we drop 4 support folks don't get untested releases)

**Comment by nburt** [comment]
@thomas-mcdonald just wanted to check in on this pr. Do you have a sense for when it could be merged? I'd tried to work on https://github.com/RolifyCommunity/rolify/issues/528 but the tests kept hanging. Would this PR resolve that?

**Comment by stevehill1981** [comment]
I've added these changes to my PR #537 because the builds at least pass this way.

**Comment by thomas-mcdonald** [comment]
I'm not convinced Hakiri is adding any value with the dependency scanning, but I've reverted the dep declaration for now. With it's current configuration I don't think we can't release a version of Rolify that allows Rails < 5.2

**Comment by thomas-mcdonald** [comment]
@EppO if we land this, I can get a couple more of the deprecation / recent Rails support PRs in and we can cut 5.3 as a maintenance fix

**Comment by thomas-mcdonald** [comment]
Making an executive decision and merging this so master is green / can land other PRs

**Pull request merged**
