### PR TITLE
active_record/role_adapter.rb improvements

### PR DESCRIPTION
**Pull request by kinnalru**
relation.role_ids |= [role.id] works extremely slow when 10000 roles attached. It is take about 2 minutes to add role. So this fix make it work as expected - about some ms. All tests passed.

### CODE REVIEW

**Comment by laertispappas** [comment]
@kinnalru Do you know why the previous operation is slow?

**Comment by v-kumar** [comment]
@laertispappas I just submitted a PR for the same as well.

The reason it is extremely slow is because you are reading all the role_ids as an Array and then performing a array union. Reading all the role_ids is unnecessary. Instead, we should rely on `include?` and add.

There have been three issues raised with the same issue. This PR #429, [issue 453](https://github.com/RolifyCommunity/rolify/issues/453) and another PR I just made: #468.

Here's the benchmark using the `|=` operator on role_ids array vs that of the patch:

`Baseline benchmark:

[78] pry(main)> Benchmark.bm { |x| x.report { user.role_ids |= [ 157 ] } }
       user     system      total        real
    (5.6ms)  SELECT "roles".id FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 9]]
  Role Load (9.6ms)  SELECT "roles".* FROM "roles" WHERE "roles"."id" IN (1, 3, ... 15596)
  Role Load (6.8ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1  [["user_id", 9]]
   (0.3ms)  BEGIN
  SQL (10.3ms)  INSERT INTO "users_roles" ("user_id", "role_id") VALUES ($1, $2)  [["user_id", 9], ["role_id", 157]]
   (0.6ms)  COMMIT
  5.580000   0.040000   5.620000 (  5.670546)
=> [#<Benchmark::Tms:0x00007fd6e4689da0
  @cstime=0.0,
  @cutime=0.0,
  @label="",
  @real=5.670546000124887,
  @stime=0.040000000000000036,
  @total=5.619999999999998,
  @utime=5.579999999999998>]


Patch benchmark:
[82] pry(main)> Benchmark.bm { |x| x.report { user.roles << role unless emily.roles.include?(role) } }
       user     system      total        real
    (0.2ms)  BEGIN
  SQL (0.2ms)  INSERT INTO "users_roles" ("user_id", "role_id") VALUES ($1, $2)  [["user_id", 9], ["role_id", 159]]
   (1.0ms)  COMMIT
  0.000000   0.000000   0.000000 (  0.008173)
=> [#<Benchmark::Tms:0x00007fd6e2fe5b30 @cstime=0.0, @cutime=0.0, @label="", @real=0.008173000067472458, @stime=0.0, @total=0.0, @utime=0.0>]

 `

**Comment by laertispappas** [comment]
@v-kumar Great. Thanks for explaining.

**Comment by thomas-mcdonald** [comment]
I'm going to close this out, since another PR was merged with the same fix

**Comment by aleksandrs-ledovskis** [comment]
For reference, the "another PR" is https://github.com/RolifyCommunity/rolify/pull/468

**Pull request closed without merging**
