### PR TITLE
Suggestion to optimize initial role loading by using eager loading

### PR DESCRIPTION
**Pull request by btsai**
In the meantime, I'm monkey patching our own stack.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
It appears that while this change is great for Active Record it fails on Mongoid because the `find_each` is not present.

**Comment by btsai** [comment]
Thanks for the quick feedback. Here's the fix!

**Comment by wldcordeiro** [comment]
@btsai thanks for the PR, it looks like that was hiding the real issue which is apparently that eager loading is not supported by Mongoid.

```
Problem:

         Eager loading :resource is not supported since it is a polymorphic belongs_to relation.

       Summary:

         Mongoid cannot currently determine the classes it needs to eager load when the relation is polymorphic. The parents reside in different collections so a simple id lookup is not sufficient enough.```

I'm not sure what the solution would be as I haven't used Mongoid myself.

**Comment by btsai** [comment]
Ah, yet another issue then. It looks like we have to switch on whether Mongoid or AR is being used, and then either use eager loading or not.

I also don't use Mongoid, so I'll have to check on how to check for that. Anyone else who knows how to check if using Mongoid as the ORM, could you please jump in?

Thanks!

**Comment by wldcordeiro** [comment]
Thanks for all the work @btsai I've merged your PR!

**Comment by btsai** [comment]
no worries, glad to help out.

**Pull request merged**
