### PR TITLE
Fix has_roles? method

### PR DESCRIPTION
**Pull request by mgrigajtis**
The has_roles? method was always returning true - even if the role didn't exist in the system.  This was because the if \ else statement had .present appended to it.  I have removed that and added some code that actually returns the correct value.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
There seems to be an issue with the Mongoid build @mgrigajtis if you could get the Travis build to pass I'll merge it in asap.

**Comment by mgrigajtis** [comment]
It'll have to wait until after 5pm when I get off of work, but I will work on it.

**Comment by wldcordeiro** [comment]
@mgrigajtis I think I found the issue with Travis so you may not need to do anything.

**Comment by mgrigajtis** [comment]
Great!

**Comment by wldcordeiro** [comment]
I've pushed the 3.5.1 release out to RubyGems. Fixes the issue with your fix. :)

**Comment by mgrigajtis** [comment]
Awesome!

**Pull request merged**
