### PR TITLE
Fix applied_roles when resourcify and rolify used together

### PR DESCRIPTION
**Pull request by benmaher**
Fixes Issue #244 introduced in fix for Issue #102.

### CODE REVIEW

**Comment by saizai** [comment]
Still broken in 3.5.2.

```ruby
User.first.is_admin?
  User Load (4.3ms)  SELECT  `users`.* FROM `users`   ORDER BY `users`.`id` ASC LIMIT 1
NoMethodError: undefined method `where' on an instance of Rolify::Adapter::ResourceAdapter.
	from kernel/delta/kernel.rb:78:in `where (method_missing)'
	from /Users/saizai/.rvm/gems/rbx-2.4.1/gems/rolify-3.5.2/lib/rolify/role.rb:29:in `has_role?'
	from /Users/saizai/.rvm/gems/rbx-2.4.1/gems/rolify-3.5.2/lib/rolify/dynamic.rb:12:in `define_dynamic_method'
```

**Comment by saizai** [comment]
Fix: put resourcify above rolify.

There's a mention of this buried in the wiki. I suggest adding it to the README.

**Comment by wldcordeiro** [comment]
Ah, good that you found the source of the issue I'll update the readme to mention that.

**Comment by saizai** [comment]
@wldcordeiro Thanks. :)

**Pull request closed without merging**
