### PR TITLE
Fix migration generator for Rails 6 support

### PR DESCRIPTION
**Pull request by stevehill1981**
Resubmitting this PR in favour of #513 - this approach effectively drops support for Rails versions older than 5, which seems reasonable.

### CODE REVIEW

**Comment by stevehill1981** [comment]
Seems to be a fun bit of lag retrieving dependencies for the Mongoid builds. That was the case for me locally also, I just assumed it wouldn't be a problem on Travis.

**Comment by stevehill1981** [comment]
I've dropped support for Ruby 2.3 here.

Nobody should be using that version. The only reason I'm still allowing Ruby 2.4 is because it only fell out of support a couple of days ago.

**Comment by tomca32** [comment]
I understand this isn't really being maintained anymore, but I still hope we could get some of this stuff in.

**Comment by stevehill1981** [comment]
> I understand this isn't really being maintained anymore, but I still hope we could get some of this stuff in.

In the meantime, do feel free to use my fork. I have hopes that the maintainers may do something soon, but I have nothing to base that on.

**Comment by thomas-mcdonald** [comment]
Hey Steve - thanks for your work and the patience with getting this landed, and sorry for having this sit around for so long.

I think I prefer your approach outlined in #513. While I'd like to drop support for unsupported / EOL Ruby + Rails, I would like to get one maintenance release out with the current performance patches sitting on master before we officially remove support in a new major version.

**Comment by stevehill1981** [comment]
@thomas-mcdonald It's fine :) I'm never likely to criticise anyone for not having enough time to work on open source projects. I'll close this PR and re-open the other one, if you haven't already done so.

**Comment by stevehill1981** [comment]
@thomas-mcdonald I've opened #539 which re-implements the changes from #513 - I was hasty and deleted the previous branch that PR was based on.

**Pull request closed without merging**
