### PR TITLE
Prepare release 5.2.0

### PR DESCRIPTION
**Pull request by rameshdavid**
It would seem that https://github.com/RolifyCommunity/rolify/pull/393 did not make it to a new release.

### CODE REVIEW

**Comment by wldcordeiro** [comment]
Hmm, it seems like we have some build troubles. I tried re-running the Travis build and had no success. Care to look at it @rameshdavid either myself or @lorefnon could do final prep and release.

**Comment by mikwat** [comment]
I've fixed the specs. Please take a look: https://github.com/RolifyCommunity/rolify/pull/413

**Comment by wldcordeiro** [comment]
@mikwat I'm going to pull in #413 later today, as well as your other PR if it's passing with the changes in #413 along with this one and prep and tag 5.2.0

**Comment by mikwat** [comment]
Great, thanks @wldcordeiro !

**Comment by mikwat** [comment]
Any update @wldcordeiro ?

**Comment by wldcordeiro** [comment]
Apologies for the long delay in review. Been very busy with day job stuff and don't do much Ruby work. Could you rebase this and I'll see if CI passes. 😄

**Comment by mikwat** [comment]
This can probably be closed since https://github.com/RolifyCommunity/rolify/pull/478 merged.

**Pull request closed without merging**
