### PR TITLE
Prepare version 5.2.0

### PR DESCRIPTION
**Pull request by mikwat**
There have been a lot of changes since 5.1.0 There was an attempt at this back in 2016:  https://github.com/RolifyCommunity/rolify/pull/405 Hoping to see it through this time.

@wldcordeiro

### CODE REVIEW

**Comment by wldcordeiro** [comment]
@mikwat CI seems to fail. I'd love to get some help from some more active Ruby developers in getting this to work with Rails 5 and only the other supported versions.

**Comment by mikwat** [comment]
@wldcordeiro Strange that CI passed on master 24 days ago... let me try to figure out what's going on.

**Comment by mikwat** [comment]
@wldcordeiro CI passing now!

**Comment by mikwat** [comment]
Sorry to bug you @wldcordeiro, but I'd really like to move this forward. Please take another look.

**Comment by mikwat** [comment]
Great, thanks @wldcordeiro!

**Pull request merged**
